### PR TITLE
Proposed outlier exclusion for Tobii labs

### PR DESCRIPTION
**Pull request by yuen-francis**
image

Added filters of 0 <= x <= monitor width and 0 <= y <= monitor height to exclude all observations that is outside the bounds of the monitor as a possible solution to issue #31. Unsure if this is an appropriate solution as there is a huge loss of data after this filter, and I am not familiar with how Tobii works. Any suggestions/feedback? Graph is the distribution of gaze from Tobii labs after this filter; still some mysterious outliers but much better than before.

### CODE REVIEW

**Comment by mcfrank** [comment]
Thanks! As I mentioned in #31, eventually this should go in peekds, but
thanks for fixing here.

Looks like you still have some negative X points though? Are those the
mysterious points you are mentioning? The other fixations within the screen
coordinates are to be expected - sometimes kids will just look at other
stuff...

**Comment by yuen-francis** [comment]
I figured out why there are still negative coordinates: the plot is corrected so that 0,0 reflects the corner of the stimuli rather than the screen, so as long as the negative value does not exceed the blank space between stimuli and the edge of the screen (which is essentially [width of screen - width of video]/2), it is a valid datapoint that reflects looking at category "other".

**Comment by mcfrank** [comment]
Oh interesting, thanks for clarifying. A broader question is whether this
is desired behavior or if we want to clip the xy data to be within the
stimulus space...

**Comment by yuen-francis** [comment]
My intuition is to trim it, the logic here being that if they aren't looking at the stimuli, it's effectively the same as not looking at the screen. We can imagine a similar scenario where the stimuli occupies the entire screen, in which case any gaze that exceeds the stimuli dimensions is effectively looking at something other than the screen. Unless there are reasons to not simply clip it?

**Comment by mcfrank** [comment]
No, that seems fine t me!

**Comment by yuen-francis** [comment]
Added the new xy_trim() function to all import.R scripts. Verified functionality via data_integrity.Rmd for SMI and Tobii labs using the reprocessed xy_datasets. Could not reproduce eyelink labs because of missing package, but should work the same way as long as eyelink also has origin top left like the other labs

**Comment by yuen-francis** [comment]
image
image
For quick reference, this is the gaze distribution for SMI and Tobii after xy_trim without manually fixing the axis

**Pull request merged**
